repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: flake8
    - id: mixed-line-ending
      args:
      - --fix=lf
    - id: trailing-whitespace
  
  - repo: https://github.com/psf/black
      rev: 23.10.0
      hooks:
        - id: black
          language_version: python3.11
          args: ['--quiet']
          name: black-format
          stages: [commit]

  - repo: local
    hooks:
      - id: test_app
        stages: [commit]
        types: [python]
        name: test_app
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
