repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.25.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: test
        name: "Run Tests"
        entry: python -m unittest discover -s tests
        language: system
        stages: [commit]
